// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8HN4BigoCwnpcUBicA3zrvJ714kukqI',
    appId: '1:450584437388:web:0688688f4424ffa23891a9',
    messagingSenderId: '450584437388',
    projectId: 'tacoexpress-a4ba6',
    authDomain: 'tacoexpress-a4ba6.firebaseapp.com',
    storageBucket: 'tacoexpress-a4ba6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7MSJCifi3qiMVrmEpV-Pl6AN_3ypa050',
    appId: '1:450584437388:android:61770b3d2f44f7ac3891a9',
    messagingSenderId: '450584437388',
    projectId: 'tacoexpress-a4ba6',
    storageBucket: 'tacoexpress-a4ba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyLKwVMtE2GPVBIT7zm0qJ_n4pdbloUmQ',
    appId: '1:450584437388:ios:e04d63d894d165123891a9',
    messagingSenderId: '450584437388',
    projectId: 'tacoexpress-a4ba6',
    storageBucket: 'tacoexpress-a4ba6.firebasestorage.app',
    iosBundleId: 'com.example.tacoExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyLKwVMtE2GPVBIT7zm0qJ_n4pdbloUmQ',
    appId: '1:450584437388:ios:e04d63d894d165123891a9',
    messagingSenderId: '450584437388',
    projectId: 'tacoexpress-a4ba6',
    storageBucket: 'tacoexpress-a4ba6.firebasestorage.app',
    iosBundleId: 'com.example.tacoExpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO8HN4BigoCwnpcUBicA3zrvJ714kukqI',
    appId: '1:450584437388:web:9ba5a07cbd5c22e83891a9',
    messagingSenderId: '450584437388',
    projectId: 'tacoexpress-a4ba6',
    authDomain: 'tacoexpress-a4ba6.firebaseapp.com',
    storageBucket: 'tacoexpress-a4ba6.firebasestorage.app',
  );
}
